In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.7092858 ,  0.17518751,  0.8325821 , -0.6609273 , -0.14033899,
         0.13255273,  0.54622495, -0.08804033,  0.90134454, -0.25428   ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.03970677, 0.09615821, 0.18556209, 0.04167411, 0.07013825,
        0.0921447 , 0.13935606, 0.07390401, 0.1987707 , 0.06258512]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3843951

In [8]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0676 - accuracy: 0.9787
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0568 - accuracy: 0.9815
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0529 - accuracy: 0.9825
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0474 - accuracy: 0.9844
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0449 - accuracy: 0.9848
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0421 - accuracy: 0.9862
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0394 - accuracy: 0.9868
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0377 - accuracy: 0.9872
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0334 - accuracy: 0.9883
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.033

In [13]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0760 - accuracy: 0.9789


[0.07598661631345749, 0.9789000153541565]

In [14]:
prob_model = tf.keras.Sequential([model,tf.keras.layers.Softmax()])

In [15]:
prob_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.71847865e-12, 2.49904291e-13, 1.04465867e-10, 2.02482852e-06,
        9.30053839e-18, 5.61193453e-11, 9.07255418e-18, 9.99997973e-01,
        1.97781749e-10, 2.90059035e-08],
       [1.87338361e-12, 1.05223288e-08, 1.00000000e+00, 5.19616902e-13,
        6.37712785e-31, 7.31041357e-15, 1.96088927e-13, 2.64276908e-25,
        1.81376818e-13, 6.60858264e-25],
       [5.15032496e-11, 9.99974012e-01, 1.12433036e-05, 3.15722182e-09,
        7.96768973e-07, 5.79115822e-09, 4.36228387e-09, 1.38486348e-05,
        1.51042457e-07, 1.68002112e-09],
       [1.00000000e+00, 4.45899150e-15, 4.97282642e-08, 8.78666306e-11,
        2.84920498e-13, 1.64435063e-10, 2.85686058e-10, 4.60925342e-09,
        1.04655503e-11, 1.02422772e-08],
       [1.50648560e-08, 1.52115206e-17, 3.46685658e-09, 5.25581152e-13,
        9.99833226e-01, 1.23154195e-10, 2.31627517e-09, 1.82394047e-07,
        9.37329148e-08, 1.66466270e-04]], dtype=float32)>